services:
  grafana:
    container_name: grafana
    build:
      context: ./.config
      args:
        grafana_image: grafana/grafana # Assuming you're using the OSS image
        grafana_version: latest
        development: false
    ports:
      - 3000:3000
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-greptimedb-datasource # Mount your GreptimeDB plugin
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/grafana-greptimedb-datasource # Mount your GreptimeDB plugin source
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/login"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - GF_LOG_LEVEL=debug
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=true # Allow your local plugin
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource # Install the ClickHouse plugin
      - GF_DEFAULT_APP_MODE=development # Recommended for local plugin development
    networks:
      - grafana

  clickhouse-server:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION:-24.7-alpine}
    container_name: clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "clickhouse-client", "--host", "clickhouse-server", "--query", "SELECT 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - grafana

  test-data-loader:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION:-24.7-alpine}
    container_name: test-data-loader
    entrypoint: ["clickhouse-client", "--host", "clickhouse-server", "--queries-file", "/dev/shm/property-prices.sql"]
    depends_on:
      clickhouse-server:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./tests/fixtures/property-prices.sql:/dev/shm/property-prices.sql
    networks:
      - grafana

networks:
  grafana: 
