services:
  grafana:
    container_name: grafana
    build:
      context: ./.config
      args:
        grafana_image: grafana/grafana # Assuming you're using the OSS image
        grafana_version: latest
        development: false
    ports:
      - 3000:3000
    volumes:
      - ./dist:/var/lib/grafana/plugins/info8fcc-greptimedb-datasource # Mount your GreptimeDB plugin
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/info8fcc-greptimedb-datasource # Mount your GreptimeDB plugin source
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/login"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - GF_LOG_LEVEL=debug
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=true # Allow your local plugin
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource # Install the ClickHouse plugin
      - GF_DEFAULT_APP_MODE=development # Recommended for local plugin development
    networks:
      - grafana


networks:
  grafana: 
