version: '3.1'

services:
  greptimedb:
    image: docker.io/greptime/greptimedb:v0.11.0
    container_name: greptimedb_info8fcc
    command: standalone start --http-addr=0.0.0.0:4000 --rpc-addr=0.0.0.0:4001 --mysql-addr=0.0.0.0:4002
    ports:
      - 4000:4000
      - 4001:4001
      - 4002:4002
    networks:
      - datasource-network

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus_info8fcc
    ports:
      - 9090:9090
    networks:
      - datasource-network
    volumes:
      - ./prometheus-greptimedb.yml:/etc/prometheus/prometheus.yml:ro

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter_info8fcc
    # ports:
    #   - 9100:9100
    command:
      - '--path.rootfs=/'
    networks:
      - datasource-network

  grafana:
    image: docker.io/greptime/grafana-greptimedb:latest
    container_name: grafana_info8fcc
    ports:
      - 3000:3000
    volumes:
      - ../provisioning:/etc/grafana/provisioning
    networks:
      - datasource-network

networks:
  datasource-network:
